# Generated by Django 3.2.6 on 2021-08-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0002_auto_20210825_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='text0',
            new_name='texto',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
