# Generated by Django 3.2.6 on 2021-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Juego', '0003_auto_20210825_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='puntos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
